# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

# デフォルトで遅延読み込み
apply = ["lazy"]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

[templates]
lazy = "{% for file in files %}zsh-defer -mpr source \"{{ file }}\"\n{% endfor %}"
very_lazy = "{% for file in files %}zsh-defer -t 5 -mpr source \"{{ file }}\"\n{% endfor %}"

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["source"]
[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"

[plugins.powerlevel10k]
github = "romkatv/powerlevel10k"
apply = ["source"]

[plugins.zsh-abbr]
github = "olets/zsh-abbr"
[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"
apply = ["lazy"]
[plugins.git-open]
github = "paulirish/git-open"
apply = ["very_lazy"]

[plugins.aws_zsh_completer]
remote = "https://raw.githubusercontent.com/aws/aws-cli/v2/bin/aws_zsh_completer.sh"
apply = ["very_lazy"]
[plugins.delta]
remote = "https://raw.githubusercontent.com/dandavison/delta/master/etc/completion/completion.zsh"
apply = ["very_lazy"]

[plugins.dotfiles-lazy]
local = "~/.config/zsh"
use = ["local.zsh", "functions.zsh", "alias.zsh"]
[plugins.dotfiles-sync]
local = "~/.config/zsh"
use = ["options.zsh", "sync.zsh", "wezterm.sh"]
apply = ["source"]
[plugins.dotfiles-very-lazy]
local = "~/.config/zsh"
use = ["plugins.zsh"]
apply = ["very_lazy"]
