# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

# デフォルトで遅延読み込み
apply = ["defer"]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"

[plugins.powerlevel10k]
github = "romkatv/powerlevel10k"
apply = ["source"]

[plugins.zsh-abbr]
github = "olets/zsh-abbr"
[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"
apply = ["source"]
[plugins.git-open]
github = "paulirish/git-open"

[plugins.aws_zsh_completer]
remote = "https://raw.githubusercontent.com/aws/aws-cli/v2/bin/aws_zsh_completer.sh"
[plugins.delta]
remote = "https://raw.githubusercontent.com/dandavison/delta/master/etc/completion/completion.zsh"

[plugins.dotfiles-defer]
local = "~/.config/zsh"
use = ["alias.zsh", "local.zsh", "functions.zsh", "plugins.zsh"]
[plugins.dotfiles-sync]
local = "~/.config/zsh"
use = ["sync.zsh", "options.zsh"]
apply = ["source"]

[plugins.zsh-vi-mode]
github = "jeffreytse/zsh-vi-mode"
apply = ["source"]
