#!/usr/bin/env zsh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

LEFT_HALF=16:10:0:0:5:16
RIGHT_HALF=16:10:5:0:5:16
TOP_RIGHT=16:10:5:0:5:8
BOTTOM_RIGHT=16:10:5:8:5:8

LEFT_70=16:10:0:0:7:16
RIGHT_70=16:10:3:0:7:16
FULL=1:1:0:0:1:1

# float apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Karabiner.*$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Preview$" manage=off
yabai -m rule --add app="^Bitwarden$" manage=off
yabai -m rule --add app="^KeePassXC$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="カレンダー" manage=off
yabai -m rule --add app="^Calendar.*$" manage=off
yabai -m rule --apply

# global settings
yabai -m config \
  external_bar off:40:0 \
  menubar_opacity 1.0 \
  mouse_follows_focus on \
  focus_follows_mouse off \
  display_arrangement_order default \
  window_origin_display default \
  window_placement second_child \
  window_zoom_persist on \
  window_shadow on \
  window_animation_duration 0.0 \
  window_animation_easing ease_out_circ \
  window_opacity_duration 0.0 \
  active_window_opacity 1.0 \
  normal_window_opacity 0.90 \
  window_opacity off \
  insert_feedback_color 0xffd75f5f \
  split_ratio 0.50 \
  split_type auto \
  auto_balance off \
  top_padding 12 \
  bottom_padding 12 \
  left_padding 12 \
  right_padding 12 \
  window_gap 8 \
  layout bsp \
  mouse_modifier alt \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap

yabai -m signal --add event=display_changed action="$HOME/.config/yabai/display_changed.sh"
yabai -m space 1 --layout float
$HOME/.config/yabai/display_changed.sh

echo "yabai configuration loaded.."
