#!/bin/bash

remote_url=$(git remote get-url origin 2>/dev/null)

if [ $? -ne 0 ]; then
  echo "Not inside a Git repository or 'origin' remote not found"
fi

repo_name=$(basename -s .git $remote_url)

if [[ $remote_url =~ ^git@ ]]; then
  org_name=$(echo $remote_url | sed -E 's#^git@[^:]+:([^/]+)/.+$#\1#')
elif [[ $remote_url =~ ^https:// ]]; then
  org_name=$(echo $remote_url | sed -E 's#^https://[^/]+/([^/]+)/.+$#\1#')
else
  echo "Unrecognized URL format ${remote_url}"
  exit 1
fi

branch=$(git symbolic-ref HEAD | cut -d "/" -f 3-)

if [[ $remote_url =~ bitbucket.org ]]; then
  url="https://bitbucket.org/${org_name}/${repo_name}/pull-requests/new?source=${branch}&t=1"
elif [[ $remote_url =~ github.com ]]; then
  url="https://github.com/${org_name}/${repo_name}/pull/new/${branch}"
fi

echo $url
open $url
