#!/bin/zsh -u

# https://qiita.com/koara-local/items/eae7942131e53cb8031a

current_branch=$(git branch | grep "^\*")

if [[ ! "$current_branch" =~ .*/[A-Z]+-[0-9]+.* ]]; then
    exit 0
fi

# e.g. feature/AAA-123-xxx-hogehoge -> AAA-123
issue_id=$(echo "$current_branch" | sed -E 's@^.*/([A-Z]+-[0-9]+).*$@\1@')

commit_message=$(head -n 1 $1)

if [[ "$commit_message" =~ '^[A-Z]+-[0-9]+ .*$' ]]; then
  # issue idがすでにある場合置き換える
  sed -i -E "1 s@^[A-Z]+-[0-9]+ (.*)\$@${issue_id} \1@" $1
elif [[ ! $(head -n 1 $1 | grep "$issue_id") ]]; then
  # 頭にissue idをつける
  sed -i -E "1 s@(.*)@${issue_id} \1@" $1
fi
