[keyboard]
bindings = [
  # Control + <key>
  { chars = "\u001B[13;5u",   key = "Return", mods = "Control" },
  { chars = "\u001B[27;5;9~", key = "Tab",    mods = "Control" },
  { chars = "\u001B[27;6;9~", key = "Tab",    mods = "Control|Shift" },

  # Control + <letter>
  { chars = "\u001B[104;5u",  key = "H",      mods = "Control" },
  { chars = "\u001B[105;5u",  key = "I",      mods = "Control" },
  { chars = "\u001B[106;5u",  key = "J",      mods = "Control" },
  { chars = "\u001B[109;5u",  key = "M",      mods = "Control" },

  # Control + Shift + <letter>
  { chars = "\u001B[65;6u",   key = "A",      mods = "Control|Shift" },
  { chars = "\u001B[68;6u",   key = "D",      mods = "Control|Shift" },
  { chars = "\u001B[69;6u",   key = "E",      mods = "Control|Shift" },
  { chars = "\u001B[71;6u",   key = "G",      mods = "Control|Shift" },
  { chars = "\u001B[72;6u",   key = "H",      mods = "Control|Shift" },
  { chars = "\u001B[73;6u",   key = "I",      mods = "Control|Shift" },
  { chars = "\u001B[74;6u",   key = "J",      mods = "Control|Shift" },
  { chars = "\u001B[75;6u",   key = "K",      mods = "Control|Shift" },
  { chars = "\u001B[76;6u",   key = "L",      mods = "Control|Shift" },
  { chars = "\u001B[77;6u",   key = "M",      mods = "Control|Shift" },
  { chars = "\u001B[79;6u",   key = "O",      mods = "Control|Shift" },
  { chars = "\u001B[80;6u",   key = "P",      mods = "Control|Shift" },
  { chars = "\u001B[81;6u",   key = "Q",      mods = "Control|Shift" },
  { chars = "\u001B[82;6u",   key = "R",      mods = "Control|Shift" },
  { chars = "\u001B[83;6u",   key = "S",      mods = "Control|Shift" },
  { chars = "\u001B[84;6u",   key = "T",      mods = "Control|Shift" },
  { chars = "\u001B[87;6u",   key = "W",      mods = "Control|Shift" },
  { chars = "\u001B[88;6u",   key = "X",      mods = "Control|Shift" },
  { chars = "\u001B[89;6u",   key = "Y",      mods = "Control|Shift" },
  { chars = "\u001B[90;6u",   key = "Z",      mods = "Control|Shift" },

  # Control + <number>
  { chars = "\u001B[49;5u",   key = "Key1",   mods = "Control" },
  { chars = "\u001B[50;5u",   key = "Key2",   mods = "Control" },
  { chars = "\u001B[51;5u",   key = "Key3",   mods = "Control" },
  { chars = "\u001B[52;5u",   key = "Key4",   mods = "Control" },
  { chars = "\u001B[53;5u",   key = "Key5",   mods = "Control" },
  { chars = "\u001B[54;5u",   key = "Key6",   mods = "Control" },
  { chars = "\u001B[55;5u",   key = "Key7",   mods = "Control" },
  { chars = "\u001B[56;5u",   key = "Key8",   mods = "Control" },
  { chars = "\u001B[57;5u",   key = "Key9",   mods = "Control" },
  { chars = "\u001B[48;6u",   key = "Key0",   mods = "Control|Shift" },
  { chars = "\u001B[49;6u",   key = "Key1",   mods = "Control|Shift" },
  { chars = "\u001B[50;6u",   key = "Key2",   mods = "Control|Shift" },
  { chars = "\u001B[51;6u",   key = "Key3",   mods = "Control|Shift" },
  { chars = "\u001B[52;6u",   key = "Key4",   mods = "Control|Shift" },
  { chars = "\u001B[53;6u",   key = "Key5",   mods = "Control|Shift" },
  { chars = "\u001B[54;6u",   key = "Key6",   mods = "Control|Shift" },
  { chars = "\u001B[55;6u",   key = "Key7",   mods = "Control|Shift" },
  { chars = "\u001B[56;6u",   key = "Key8",   mods = "Control|Shift" },
  { chars = "\u001B[57;6u",   key = "Key9",   mods = "Control|Shift" },
]
